FROM node:alpine

WORKDIR /usr/src/app

COPY . .

RUN npm install

RUN npm run build

EXPOSE 3000

CMD ["sh", "-c", "npx prisma generate --force-reset && npx prisma db push --force-reset && npm run start:dev"]